# Given two strings s and t which consist of only lowercase letters.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Find the letter that was added in t.


def find_difference(s, t):

    dic = {}

    for char in s:
        dic[char] = dic.get(char, 0) + 1

    for char in t:
        if dic.get(char, 0) == 0:
            return char
        else:
            dic[char] -= 1